#!/bin/csh

# Switch to fort_src directory

cd tfdcisd/fort_src

# Use f2py to form the python modules for the Covariant CISD

#f2py -c --verbose --opt='-O4' -m ThermalCISD ThermalCISD.f90 --fcompiler=pg --f90flags="-openmp" -lgomp -lblas
#f2py -c --verbose --opt='-O4' -m ExpVals ExpVals.f90 --fcompiler=pg --f90flags="-openmp" -lgomp -lblas

# With openmp
f2py -c --verbose --opt='-O4' -m ThermalCISD ThermalCISD.f90 --fcompiler=gnu95 --f90flags="-fopenmp" -lgomp -lblas
f2py -c --verbose --opt='-O4' -m ExpVals ExpVals.f90 --fcompiler=gnu95 --f90flags="-fopenmp" -lgomp -lblas

# Without openmp
# f2py -c --verbose --opt='-O4' -m ThermalCISD ThermalCISD.f90 --fcompiler=gnu95 -lblas
# f2py -c --verbose --opt='-O4' -m ExpVals ExpVals.f90 --fcompiler=gnu95 -lblas
cp *.so ../

cd ../../
